In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import functools as ft
import numpy as np
from wordcloud import WordCloud, STOPWORDS
from collections import Counter
import re
import nltk

In [2]:
severe_combine=  pd.read_csv('../data/severe_new.csv')

C:\Users\dhana\AppData\Local\Temp\ipykernel_18680\2511865563.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  severe_combine=  pd.read_csv('../data/severe_new.csv')

In [3]:
severe_combine.columns

Index(['VAERS_ID', 'STATE', 'AGE_YRS', 'SEX', 'SYMPTOM_TEXT', 'DIED',
       'DATEDIED', 'L_THREAT', 'ER_VISIT', 'HOSPITAL', 'HOSPDAYS', 'X_STAY',
       'DISABLE', 'RECOVD', 'VAX_DATE', 'ONSET_DATE', 'NUMDAYS', 'LAB_DATA',
       'OTHER_MEDS', 'CUR_ILL', 'HISTORY', 'PRIOR_VAX', 'SPLTTYPE',
       'FORM_VERS', 'TODAYS_DATE', 'BIRTH_DEFECT', 'OFC_VISIT', 'ER_ED_VISIT',
       'ALLERGIES', 'VAX_TYPE', 'VAX_MANU', 'VAX_LOT', 'VAX_DOSE_SERIES',
       'VAX_ROUTE', 'VAX_SITE', 'VAX_NAME', 'SYMPTOM1', 'SYMPTOM2', 'SYMPTOM3',
       'SYMPTOM4', 'SYMPTOM5', 'V_NAME'],
      dtype='object')

In [4]:
female = severe_combine.loc[severe_combine['SEX']=='F']

In [5]:
female

,VAERS_ID,STATE,AGE_YRS,SEX,SYMPTOM_TEXT,DIED,DATEDIED,L_THREAT,ER_VISIT,HOSPITAL,...,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5,V_NAME
2,902479,KS,46.0,F,rPfizer-BionNTech COVID-19 Vaccine EUA 5-7 mi...,NaN,NaN,NaN,NaN,Y,...,1,IM,LA,COVID19 (COVID19 (PFIZER-BIONTECH)),Chest pain,Feeling abnormal,Flushing,Intensive care,NaN,COVID19
3,902491,NE,41.0,F,Within a few minutes of receiving the COVID 19...,NaN,NaN,NaN,NaN,NaN,...,1,IM,NaN,COVID19 (COVID19 (PFIZER-BIONTECH)),Blood pressure increased,Dizziness,Dyspnoea,Erythema,Headache,COVID19
5,902505,KS,39.0,F,"Patient felt facial flushing, pounding in ches...",NaN,NaN,NaN,NaN,NaN,...,1,IM,RA,COVID19 (COVID19 (PFIZER-BIONTECH)),Blood pressure increased,Ear discomfort,Flushing,Palpitations,Paraesthesia,COVID19
6,902557,AK,32.0,F,1750- IM injection ot R Deltoid. She was sitt...,NaN,NaN,NaN,NaN,NaN,...,1,IM,RA,COVID19 (COVID19 (PFIZER-BIONTECH)),Blood glucose normal,Blood test,Dyspnoea,Erythema,Flushing,COVID19
7,902648,CA,26.0,F,diffuse rash at anterior and right lateral nec...,NaN,NaN,NaN,NaN,NaN,...,1,IM,RA,COVID19 (COVID19 (PFIZER-BIONTECH)),Feeling hot,Rash,NaN,NaN,NaN,COVID19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297926,2516427,NJ,NaN,F,Someone I know (adult) got Cushing's Syndrome ...,NaN,NaN,NaN,NaN,Y,...,3,NaN,NaN,COVID19 (COVID19 (PFIZER-BIONTECH)),Abdominal distension,Blood glucose,Body height,Cushing's syndrome,Laboratory test,COVID19
297927,2516428,CA,72.0,F,With her very last COVID shot she had a flu sh...,NaN,NaN,NaN,NaN,NaN,...,5,OT,LA,COVID19 (COVID19 (PFIZER-BIONTECH)),Balance disorder,Dementia Alzheimer's type,Disturbance in attention,Dizziness,Electroencephalogram,COVID19
297929,2516432,PA,68.0,F,After the initial vaccination she could not wa...,NaN,NaN,NaN,NaN,NaN,...,1,NaN,RA,COVID19 (COVID19 (PFIZER-BIONTECH)),Arthritis,Gait inability,Investigation,NaN,NaN,COVID19
297931,2516440,NaN,44.0,F,I felt as if my bladder was hit by a truck plu...,NaN,NaN,NaN,NaN,NaN,...,1,NaN,RA,COVID19 (COVID19 (PFIZER-BIONTECH)),Bladder discomfort,Burning sensation,NaN,NaN,NaN,COVID19
297955,2516518,NaN,NaN,F,DEAD; This spontaneous report received from a ...,Y,5/17/2021,NaN,NaN,NaN,...,1,NaN,NaN,COVID19 (COVID19 (JANSSEN)),Death,NaN,NaN,NaN,NaN,COVID19

In [6]:
a = female.SYMPTOM1.value_counts().to_frame()

In [7]:
a = a.loc[a['SYMPTOM1']>1000]

In [8]:
a.reset_index(inplace = True)

In [9]:
b = female.SYMPTOM2.value_counts().to_frame()

In [10]:
b= b.loc[b['SYMPTOM2'] >1000]

In [11]:
b.reset_index(inplace = True)

In [12]:
c = female.SYMPTOM3.value_counts().to_frame()
c = c.loc[c['SYMPTOM3']>1000]

In [13]:
c.reset_index(inplace = True)

In [14]:
dfs = [a, b, c]
symptoms = ft.reduce(lambda left, right: pd.merge(left, right, on='index'), dfs)

In [15]:
symptoms

                   index  SYMPTOM1  SYMPTOM2  SYMPTOM3
0               COVID-19     15673      3585      1814
1              Dizziness      6058      5133      3432
2                 Chills      5375      4536      2314
3             Blood test      5149      3545      1403
4       Chest discomfort      2895      1930      1085
5             Chest pain      2583      2892      1958
6               Dyspnoea      2552      4514      4333
7                Fatigue      2449      4693      5177
8               Headache      2406      4490      5049
9                   Rash      2191      2278      2090
10                 Cough      2062      3870      2395
11  Condition aggravated      1854      1810      1291
12              Pruritus      1718      2146      1839
13         Hypoaesthesia      1552      1567      1369
14             Urticaria      1029      1412      1414
15             Diarrhoea      1017      1606      1461
16       Lymphadenopathy      1004      1180      1022

In [16]:
symptoms.to_csv('../data/symptomsf_tab.csv', index=False)

In [17]:
male = severe_combine.loc[severe_combine['SEX']=='M']

In [18]:
d = male.SYMPTOM1.value_counts().to_frame()

In [19]:
d = d.loc[d['SYMPTOM1']>1000]

In [20]:
d.reset_index(inplace = True)

In [21]:
d

                        index  SYMPTOM1
0                    COVID-19     13168
1                    Asthenia      4007
2                  Arthralgia      3587
3                   Dizziness      2435
4                       Death      2419
5                  Blood test      2325
6                  Chest pain      2003
7           Unevaluable event      1916
8                      Chills      1804
9              Abdominal pain      1374
10  Acute respiratory failure      1352
11        Acute kidney injury      1203
12               Bell's palsy      1176
13      Anticoagulant therapy      1047

In [22]:
e = male.SYMPTOM2.value_counts().to_frame()

In [23]:
e = e.loc[e['SYMPTOM2']>1000]

In [24]:
e.reset_index(inplace = True)

In [25]:
e

                       index  SYMPTOM2
0   SARS-CoV-2 test positive      4017
1                   COVID-19      3241
2                   Dyspnoea      2335
3                      Cough      2243
4                 Chest pain      2108
5                      Death      1950
6                  Dizziness      1842
7                     Chills      1727
8                    Fatigue      1615
9                 Blood test      1573
10                  Headache      1488
11                  Asthenia      1263

In [26]:
f= male.SYMPTOM3.value_counts().to_frame()

In [27]:
f = f.loc[f['SYMPTOM3']>1000]

In [28]:
f.reset_index(inplace = True)

In [29]:
f

                            index  SYMPTOM3
0                        Dyspnoea      2305
1                         Fatigue      1960
2        SARS-CoV-2 test positive      1926
3                        Headache      1608
4                        COVID-19      1499
5                           Cough      1420
6                      Chest pain      1366
7                       Dizziness      1309
8  Vaccine breakthrough infection      1102

In [30]:
dfs = [d, e, f]
symptoms_male = ft.reduce(lambda left, right: pd.merge(left, right, on='index'), dfs)

In [31]:
symptoms_male

        index  SYMPTOM1  SYMPTOM2  SYMPTOM3
0    COVID-19     13168      3241      1499
1   Dizziness      2435      1842      1309
2  Chest pain      2003      2108      1366

In [32]:
symptoms_male.to_csv('../data/severe_male.csv', index=False)

In [33]:
janssen_symp = severe_combine.loc[severe_combine['VAX_MANU']=='JANSSEN']

In [34]:
js = janssen_symp.SYMPTOM1.value_counts().to_frame()

In [35]:
js

                              SYMPTOM1
COVID-19                          2307
Arthralgia                        1132
Asthenia                           945
Blood test                         816
Dizziness                          815
...                                ...
Paranoia                             1
Aortic aneurysm repair               1
Morphoea                             1
Abnormal sleep-related event         1
Catheter placement                   1

[1657 rows x 1 columns]

In [36]:
js.loc[js['SYMPTOM1']>=500]

                SYMPTOM1
COVID-19            2307
Arthralgia          1132
Asthenia             945
Blood test           816
Dizziness            815
Chills               741
Death                614
Abdominal pain       570

In [37]:
js2= janssen_symp.SYMPTOM2.value_counts().to_frame()

In [39]:
js2.loc[js2['SYMPTOM2']>=500]

                          SYMPTOM2
SARS-CoV-2 test positive       767
Headache                       694
Dizziness                      680
Chills                         630
COVID-19                       610
Dyspnoea                       603
Blood test                     567
Fatigue                        534

In [41]:
js3= janssen_symp.SYMPTOM3.value_counts().to_frame()

In [42]:
js3.loc[js3['SYMPTOM3']>=500]

          SYMPTOM3
Headache       717
Dyspnoea       684
Fatigue        608